server:
  port: 8089
  session:
    timeout: 1800
  servlet-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/graduate-design-ww?characterEncoding=utf-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    max-active: 150
    max-idle: 50
    min-idle: 30
  jpa:
    show-sql: true
    properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update